{% set name = "asteval" %}
{% set version = "0.9.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bef25a973d378fda21c83a38c6292c4d0d94773f49f42073e69dbb19932bb74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm
  run:
    - python >=3.7
    - pip
    - setuptools-scm
    - numpy >=1.12
test:
  imports:
    - asteval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/newville/asteval
  license: MIT
  license_file: LICENSE
  summary: Simple and robust expressions evaluator for Python

  # The remaining entries in this section are optional, but recommended
  description: |
    asteval is a simple and robust evaluator of
    Python expressions and statements, using Python's ast module.
  doc_url: http://newville.github.io/asteval/
  dev_url: https://github.com/newville/asteval

extra:
  recipe-maintainers:
    - souravsingh
    - newville
