{% set name = "asteval" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15e63bd01fce65aded51357f7e1debc6f46100d777c372af11c27c07cb740074

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.8
    - pip
    - setuptools
    - setuptools-scm
    - numpy >=1.22
test:
  imports:
    - asteval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lmfit/asteval
  license: MIT
  license_file: LICENSE
  summary: Simple and robust expressions evaluator for Python

  # The remaining entries in this section are optional, but recommended
  description: |
    asteval is a simple and robust evaluator of
    Python expressions and statements, using Python's ast module.
  doc_url: https://lmfit.github.io/asteval/
  dev_url: https://github.com/lmfit/asteval

extra:
  recipe-maintainers:
    - souravsingh
    - newville
